FROM debian:bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    net-tools \
    iputils-ping \
    wget \
    curl \
    git \
    vim \
    && \
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y --no-install-recommends \
    nodejs \
    npm \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /test

EXPOSE 3000

CMD [ "/bin/bash" ]
