version: "3.9"
services:
  redhat:
    image: rh206147:0
    container_name: rh
    stdin_open: true
    tty: true
    volumes:
      - redhat_persistent_data:/data
      - redhat_user_configs:/root
      - redhat_system_config:/etc
      - redhat_var_data:/var
    build:
      context: .
      dockerfile: Dockerfile
volumes:
  redhat_persistent_data:
  redhat_user_configs:
  redhat_system_config:
  redhat_var_data:
